version: "3.4"

services:
  db:
    build: ./db
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  api:
    build: .
    ports:
      - 4000:4000
    environment:
      DB_HOST: db
    depends_on:
      - db
